#!/bin/bash

# Script to help retrieve Firebase credentials from Vercel
# Run this script to get step-by-step instructions

echo "=========================================="
echo "Firebase Credentials Retrieval Guide"
echo "=========================================="
echo ""
echo "Option 1: Vercel Dashboard (RECOMMENDED)"
echo "----------------------------------------"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Sign in with your GitHub account"
echo "3. Find project: 'ali' or 'appttt'"
echo "4. Click on the project"
echo "5. Go to: Settings → Environment Variables"
echo "6. Look for variables starting with: NEXT_PUBLIC_FIREBASE_"
echo "7. Copy each value"
echo ""
echo "Option 2: Install Vercel CLI and Pull"
echo "----------------------------------------"
echo "1. Install Vercel CLI: npm i -g vercel"
echo "2. Run: vercel login"
echo "3. Run: vercel link (in this directory)"
echo "4. Run: vercel env pull .env.local"
echo ""
echo "Option 3: Firebase Console"
echo "----------------------------------------"
echo "1. Go to: https://console.firebase.google.com/"
echo "2. Select your Firebase project"
echo "3. Click gear icon → Project settings"
echo "4. Scroll to 'Your apps' → Click Web app icon (</>)"
echo "5. Copy values from firebaseConfig object"
echo ""
echo "After getting credentials, edit .env.local and add:"
echo "NEXT_PUBLIC_FIREBASE_API_KEY=your-value-here"
echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=your-value-here"
echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=your-value-here"
echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=your-value-here"
echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=your-value-here"
echo "NEXT_PUBLIC_FIREBASE_APP_ID=your-value-here"
echo ""

