#!/bin/bash

# Script to help update Vercel environment variables
# This script will guide you through the process

echo "=========================================="
echo "Vercel Environment Variables Update"
echo "=========================================="
echo ""
echo "Since Vercel CLI requires authentication, please follow these steps:"
echo ""
echo "OPTION 1: Use Vercel Dashboard (Recommended)"
echo "--------------------------------------------"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Find your project and click on it"
echo "3. Go to: Settings → Environment Variables"
echo "4. Update these 6 variables:"
echo ""
echo "   NEXT_PUBLIC_FIREBASE_API_KEY"
echo "   Value: AIzaSyDPzRqV-_hGNedZoeGNtorLTGWTBMmqdkc"
echo ""
echo "   NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
echo "   Value: prj-adc-gcp-coop-test.firebaseapp.com"
echo ""
echo "   NEXT_PUBLIC_FIREBASE_PROJECT_ID"
echo "   Value: prj-adc-gcp-coop-test"
echo ""
echo "   NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
echo "   Value: prj-adc-gcp-coop-test.firebasestorage.app"
echo ""
echo "   NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
echo "   Value: 472242813268"
echo ""
echo "   NEXT_PUBLIC_FIREBASE_APP_ID"
echo "   Value: 1:472242813268:web:a4777a8929637bfcd4f0c1"
echo ""
echo "5. Select 'All Environments' for each"
echo "6. Save each variable"
echo "7. Go to Deployments → Redeploy latest"
echo ""
echo "OPTION 2: Use Vercel CLI (if authenticated)"
echo "--------------------------------------------"
echo "If you have Vercel CLI installed and logged in, run:"
echo ""
echo "  vercel env add NEXT_PUBLIC_FIREBASE_API_KEY production preview development"
echo "  # Then paste: AIzaSyDPzRqV-_hGNedZoeGNtorLTGWTBMmqdkc"
echo ""
echo "  vercel env add NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN production preview development"
echo "  # Then paste: prj-adc-gcp-coop-test.firebaseapp.com"
echo ""
echo "  # ... (repeat for all 6 variables)"
echo ""
echo "See UPDATE_VERCEL_NOW.md for detailed step-by-step instructions."
echo ""


